### PR TITLE
Removed socket prop from the stream wrap

### LINKED ISSUE #146: Broken usage with .inject
## 🐛 Bug Report

https://github.com/fastify/light-my-request/pull/99 added the `.socket` property to light-my-request, which broke any usage of this module with `inject` in fastify. Apparently, https://github.com/fastify/fastify-static/blob/9d6ef4dab0ba29dee43851ce77d33f9f26261955/index.js#L66 causes the problem to happen.

### PR DESCRIPTION
**Pull request by mcollina**
Fixes #146 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -63,7 +63,7 @@ function fastifyStatic (fastify, opts, next) {
 
     wrap.getHeader = reply.getHeader.bind(reply)
     wrap.setHeader = reply.header.bind(reply)
-    wrap.socket = request.raw.socket
+    // wrap.socket = request.raw.socket
```
Comment (kibertoad) [inline index.js:66]: should it be commented out?

Comment (mcollina) [reply index.js]: no I just dropped it, good catch!

**Comment by mcollina** [comment]
@kibertoad good to land?

**Review by kibertoad — APPROVED** [review]
