### PR TITLE
fix: if serve: false and root is not defined, only allow sending files with absolute path

### LINKED ISSUE #460: When using serve: false, root should be optional
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I just want to use the `sendFile` decorator without serving any files automatically, so I set `serve: false`. However, I still need to provide a valid path to `root`, otherwise `checkRootPathForErrors` complains. Now I resort to creating a dummy directory in tmpdir() just to keep this plugin happy, which seems a bit silly.

I think if `serve: false` is defined, `checkRootPathForErrors` should not be called at all.

### Motivation

_No response_

### Example

_No response_

### PR DESCRIPTION
**Pull request by Uzlopak**
If serve is set to false, it only allows to send files specified with an absolute path. Or else sendFile makes no sense anymore, despite that we want to allow the use of sendFile.

#### Checklist

- [ ] run `npm run test && npm run benchmark --if-present`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/main/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by ilteoood — COMMENTED** [review]
LGTM

**Comment by is2ei** [comment]
I think @climba03003 would be the right person, as he originally mentioned the security concern.

**Review by climba03003 — APPROVED** [review]
LGTM.

File: index.js [hunk 1]
```diff
@@ -19,8 +19,10 @@ send.mime.default_type = 'application/octet-stream'
 
 /** @type {import("fastify").FastifyPluginAsync<import("./types").FastifyStaticOptions>} */
 async function fastifyStatic (fastify, opts) {
-  opts.root = normalizeRoot(opts.root)
-  checkRootPathForErrors(fastify, opts.root)
+  if (opts.serve !== false) {
+    opts.root = normalizeRoot(opts.root)
+    checkRootPathForErrors(fastify, opts.root)
+  }
```
Comment (Uzlopak) [inline index.js]: I think this is wrong. If opts.serve is false i can still have a defined root.

**Review by is2ei — APPROVED** [review]
LGTM!
